import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../styles/globals.css"
import AppHeader from "@/components/app-header"
import AppFooter from "@/components/app-footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#fdfbf7] flex flex-col items-center min-h-screen text-zinc-900 ${inter.className}`}
      >
        <div className="w-[1100px]">
          <AppHeader />
          {children}
          <AppFooter />
        </div>
      </body>
    </html>
  )
}
